### ISSUE TITLE
Not getting communication between two radios

### ISSUE THREAD

**Issue by RicardoM17** [MISTLab/XbeeMav#3]
Hello and first of all thank you for reading this.

I'm having a few issues with getting this code to work.

I'm using two XBee Pro S2C Zigbee.

Using XCTU firmware on Windows I can get the two RFs talking in the same computer if I configure them with the set function as Zigbee pro vs DigiMesh. From the image in your README.md it seems that this is the one that you use, however there is also some mentions of DigiMesh?

Because my radios are different I can't use one of your profiles as it says that the firmware is not compatible, however I looked at the parameters individually and it seems that everything is roughly the same (some parameters don't exist however).

I'm testing by launching `rosrun xbee_ros_node test_controller master` and then `roslaunch xbee_ros_node xbeemav.launch` for both slave and master and I've managed to get both `roslaunch` commands to recognize the node (it prints the Node ID) and in that scenario when I send a random number it says command sent but it is never received on the other side..

With ZigBee set function and testing on XCTU on windows I can get them both talking fine on the XCTU console if I set one of the radios as coordinator, but in this scenario the roslaunch doesn't recognize them again..

Any help would be very much appreciated. 

Pinging @dastoqc 

Thanks once again!

**Comment by dastoqc** [comment]
Dear @RicardoM17,
Thank you for your interest in our code. We never tried the Zigbee series, but it seems you got them to communicate already.

In order to ensure that we always get all the devices using the right set of parameters over the whole fleet, we force the parameters back to the devices at launch: https://github.com/MISTLab/XbeeMav/blob/master/src/main.cpp#L33
Now you need to adapt the config file (https://github.com/MISTLab/XbeeMav/blob/7f675930a9103d7932e7cb706fe1892bceb07142/Resources/XBee_Config.xml) used by our node to fit the parameters of your module. This file can be extracted from XCTU.

Another options is to test with our more recent (test) branch: network_status. We commented out the self-configuration at launch to use various devices we were testing lately.

I hope this helps. Keep us posted on your experiments!
